# Generated by Django 4.1 on 2022-09-03 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='celebrity_list',
            field=models.ManyToManyField(blank=True, related_name='celebrities_list', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='movies_list',
            field=models.ManyToManyField(blank=True, related_name='movies_list', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='to_watch',
            field=models.ManyToManyField(blank=True, related_name='towatch', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='watched',
            field=models.ManyToManyField(blank=True, related_name='watched', to='movies.movie'),
        ),
    ]
