# Generated by Django 4.1 on 2022-09-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0013_alter_celebrityrole_celebrity_and_more'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='celebrity_list',
            field=models.ManyToManyField(blank=True, related_name='celebrities_list', to='actor.celebrity'),
        ),
    ]
