# Generated by Django 4.1 on 2022-09-11 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_rating_user_alter_review_user'),
        ('accounts', '0003_alter_userlist_celebrity_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='to_watch',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='watched',
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_watch', models.ManyToManyField(blank=True, related_name='towatch', to='movies.movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlist', to=settings.AUTH_USER_MODEL)),
                ('watched', models.ManyToManyField(blank=True, related_name='watched', to='movies.movie')),
            ],
        ),
    ]
