# Generated by Django 4.1 on 2022-09-03 17:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth_name', models.CharField(blank=True, max_length=200)),
                ('rank', models.CharField(default=0, max_length=5)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('avatar', models.TextField(blank=True, max_length=2000, validators=[django.core.validators.URLValidator()])),
                ('description', models.TextField(blank=True)),
                ('birth_place', models.CharField(blank=True, max_length=200)),
                ('dob', models.DateField()),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('is_married', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CelebrityRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.BooleanField(default=False)),
                ('writer', models.BooleanField(default=False)),
                ('actor', models.BooleanField(default=False)),
                ('producer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celbrity', to='actor.celebrity')),
                ('movie', models.ManyToManyField(related_name='celbrity_role', to='movies.movie')),
            ],
        ),
    ]
