# Generated by Django 4.1 on 2022-09-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_remove_celebrity_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrity',
            name='dob',
        ),
    ]
