# Generated by Django 4.1 on 2022-09-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0003_remove_celebrity_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrity',
            name='birth_name',
        ),
    ]
