# Generated by Django 4.1 on 2022-09-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0004_remove_celebrity_birth_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='birth_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
