# Generated by Django 4.1 on 2022-09-03 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0005_celebrity_birth_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 3, 18, 31, 33, 854658)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celebrity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
