# Generated by Django 4.1 on 2022-09-03 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0006_celebrity_created_at_celebrity_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 3)),
            preserve_default=False,
        ),
    ]
