# Generated by Django 4.1 on 2022-09-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0007_celebrity_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='dob',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
