# Generated by Django 4.1 on 2022-09-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0008_alter_celebrity_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='updated_at',
        ),
    ]
