# Generated by Django 4.1 on 2022-09-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0009_remove_celebrity_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='dob',
            field=models.DateField(blank=True),
        ),
    ]
