# Generated by Django 4.1 on 2022-09-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0010_alter_celebrity_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
