# Generated by Django 4.1 on 2022-09-10 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_options'),
        ('actor', '0012_celebrity_created_at_celebrity_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrityrole',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebrity', to='actor.celebrity'),
        ),
        migrations.RemoveField(
            model_name='celebrityrole',
            name='movie',
        ),
        migrations.AddField(
            model_name='celebrityrole',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='celebrity_role', to='movies.movie'),
        ),
    ]
