# Generated by Django 4.1 on 2022-09-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_season_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='season_title',
            field=models.CharField(blank=True, default='test description for movies', max_length=255),
            preserve_default=False,
        ),
    ]
