# Generated by Django 4.1 on 2022-09-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_description_alter_movie_season_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
    ]
