# Generated by Django 4.1 on 2022-09-11 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image_gallery',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video_gallery',
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_image_gallery', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_video_gallery', to='movies.movie'),
        ),
    ]
