# Generated by Django 4.1 on 2022-09-11 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_movie_image_gallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='poster_url',
            field=models.TextField(blank=True, max_length=2000, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='video_poster_url',
            field=models.TextField(blank=True, max_length=2000, validators=[django.core.validators.URLValidator()]),
        ),
    ]
