# Generated by Django 4.1 on 2022-09-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_imagegallery_poster_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallery',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='videogallery',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='image_gallery',
            field=models.ManyToManyField(blank=True, to='movies.imagegallery'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_gallery',
            field=models.ManyToManyField(blank=True, to='movies.videogallery'),
        ),
    ]
